# Generated by Django 4.2.6 on 2023-12-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conapp',
            old_name='last_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='conapp',
            old_name='position',
            new_name='note',
        ),
    ]
