# Generated by Django 4.2.6 on 2023-12-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_last_name_conapp_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conapp',
            old_name='first_name',
            new_name='name',
        ),
    ]
